[book]
authors = ["Abhinandh S"]
language = "en"
src = "docs"
# title = "Pikachu Bot"

[output.html]
admonitions = true # > [!NOTE]
site-url = "/pikachu-bot/"
additional-css = ["docs/theme/custom.css"]

[output.html.print]
enable = true    # include support for printable output
page-break = false # insert page-break after each chapter

